// <auto-generated />
using System;
using Fioo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fioo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "candidatura_status", new[] { "pendente", "aceita", "recusada", "cancelada" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "cobranca_tipo", new[] { "por_peca", "por_operacao" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "denuncia_status", new[] { "aberta", "em_analise", "resolvida", "arquivada" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "prazo_tipo", new[] { "semanal", "quinzenal", "mensal", "data_especifica" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "servico_status", new[] { "ativo", "em_andamento", "finalizado", "cancelado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "usuario_tipo", new[] { "costureiro", "fornecedor" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fioo.Entities.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaliadoId")
                        .HasColumnType("integer")
                        .HasColumnName("avaliado_id");

                    b.Property<int>("AvaliadorId")
                        .HasColumnType("integer")
                        .HasColumnName("avaliador_id");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("DataAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_avaliacao")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("Nota")
                        .HasColumnType("smallint")
                        .HasColumnName("nota");

                    b.Property<int>("ServicoId")
                        .HasColumnType("integer")
                        .HasColumnName("servico_id");

                    b.HasKey("Id");

                    b.HasIndex("AvaliadoId");

                    b.HasIndex("AvaliadorId");

                    b.HasIndex("ServicoId", "AvaliadorId", "AvaliadoId")
                        .IsUnique();

                    b.ToTable("avaliacoes", (string)null);
                });

            modelBuilder.Entity("Fioo.Entities.Candidatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCandidatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_candidatura")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ServicoId")
                        .HasColumnType("integer")
                        .HasColumnName("servico_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ServicoId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("candidaturas", (string)null);
                });

            modelBuilder.Entity("Fioo.Entities.Denuncia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDenuncia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_denuncia")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DenunciadoId")
                        .HasColumnType("integer")
                        .HasColumnName("denunciado_id");

                    b.Property<int>("DenuncianteId")
                        .HasColumnType("integer")
                        .HasColumnName("denunciante_id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descricao");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("motivo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DenunciadoId");

                    b.HasIndex("DenuncianteId");

                    b.ToTable("denuncias", (string)null);
                });

            modelBuilder.Entity("Fioo.Entities.Maquinario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("maquinarios", (string)null);
                });

            modelBuilder.Entity("Fioo.Entities.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataUpload")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_upload")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("foto_url");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("portfolios", (string)null);
                });

            modelBuilder.Entity("Fioo.Entities.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriaServico")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria_servico");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataPrazo")
                        .HasColumnType("date")
                        .HasColumnName("data_prazo");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("estado");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TipoCobranca")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_cobranca");

                    b.Property<string>("TipoPrazo")
                        .HasColumnType("text")
                        .HasColumnName("tipo_prazo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("servicos", (string)null);
                });

            modelBuilder.Entity("Fioo.Entities.ServicoMaquinario", b =>
                {
                    b.Property<int>("ServicoId")
                        .HasColumnType("integer")
                        .HasColumnName("servico_id");

                    b.Property<int>("MaquinarioId")
                        .HasColumnType("integer")
                        .HasColumnName("maquinario_id");

                    b.HasKey("ServicoId", "MaquinarioId");

                    b.HasIndex("MaquinarioId");

                    b.ToTable("servico_maquinarios", (string)null);
                });

            modelBuilder.Entity("Fioo.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnosExperiencia")
                        .HasColumnType("integer")
                        .HasColumnName("anos_experiencia");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("CpfCnpj")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cpf_cnpj");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("estado");

                    b.Property<string>("FotoPerfilUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("foto_perfil_url");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nome_usuario");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<bool>("TelefoneVisivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("telefone_visivel");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NomeUsuario")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Fioo.Entities.UsuarioMaquinario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<int>("MaquinarioId")
                        .HasColumnType("integer")
                        .HasColumnName("maquinario_id");

                    b.HasKey("UsuarioId", "MaquinarioId");

                    b.HasIndex("MaquinarioId");

                    b.ToTable("usuario_maquinarios", (string)null);
                });

            modelBuilder.Entity("Fioo.Entities.Verificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataEnvioDocumento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_envio_documento");

                    b.Property<DateTime?>("DataVerificacaoCompleta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_verificacao_completa");

                    b.Property<bool>("EtapaDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("etapa_documento");

                    b.Property<bool>("EtapaEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("etapa_email");

                    b.Property<bool>("EtapaTempo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("etapa_tempo");

                    b.Property<string>("FotoSelfieUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("foto_selfie_url");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("verificacoes", (string)null);
                });

            modelBuilder.Entity("Fioo.Entities.Avaliacao", b =>
                {
                    b.HasOne("Fioo.Entities.Usuario", "Avaliado")
                        .WithMany("AvaliacoesRecebidas")
                        .HasForeignKey("AvaliadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fioo.Entities.Usuario", "Avaliador")
                        .WithMany("AvaliacoesFeitas")
                        .HasForeignKey("AvaliadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fioo.Entities.Servico", "Servico")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliado");

                    b.Navigation("Avaliador");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("Fioo.Entities.Candidatura", b =>
                {
                    b.HasOne("Fioo.Entities.Servico", "Servico")
                        .WithMany("Candidaturas")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fioo.Entities.Usuario", "Usuario")
                        .WithMany("Candidaturas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Servico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fioo.Entities.Denuncia", b =>
                {
                    b.HasOne("Fioo.Entities.Usuario", "Denunciado")
                        .WithMany()
                        .HasForeignKey("DenunciadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fioo.Entities.Usuario", "Denunciante")
                        .WithMany("DenunciasFeitas")
                        .HasForeignKey("DenuncianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Denunciado");

                    b.Navigation("Denunciante");
                });

            modelBuilder.Entity("Fioo.Entities.Portfolio", b =>
                {
                    b.HasOne("Fioo.Entities.Usuario", "Usuario")
                        .WithMany("Portfolios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fioo.Entities.Servico", b =>
                {
                    b.HasOne("Fioo.Entities.Usuario", "Usuario")
                        .WithMany("Servicos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fioo.Entities.ServicoMaquinario", b =>
                {
                    b.HasOne("Fioo.Entities.Maquinario", "Maquinario")
                        .WithMany("Servicos")
                        .HasForeignKey("MaquinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fioo.Entities.Servico", "Servico")
                        .WithMany("Maquinarios")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maquinario");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("Fioo.Entities.UsuarioMaquinario", b =>
                {
                    b.HasOne("Fioo.Entities.Maquinario", "Maquinario")
                        .WithMany("Usuarios")
                        .HasForeignKey("MaquinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fioo.Entities.Usuario", "Usuario")
                        .WithMany("Maquinarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maquinario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fioo.Entities.Verificacao", b =>
                {
                    b.HasOne("Fioo.Entities.Usuario", "Usuario")
                        .WithOne("Verificacao")
                        .HasForeignKey("Fioo.Entities.Verificacao", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fioo.Entities.Maquinario", b =>
                {
                    b.Navigation("Servicos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Fioo.Entities.Servico", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Candidaturas");

                    b.Navigation("Maquinarios");
                });

            modelBuilder.Entity("Fioo.Entities.Usuario", b =>
                {
                    b.Navigation("AvaliacoesFeitas");

                    b.Navigation("AvaliacoesRecebidas");

                    b.Navigation("Candidaturas");

                    b.Navigation("DenunciasFeitas");

                    b.Navigation("Maquinarios");

                    b.Navigation("Portfolios");

                    b.Navigation("Servicos");

                    b.Navigation("Verificacao");
                });
#pragma warning restore 612, 618
        }
    }
}
